first commit

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -32,7 +32,12 @@ jobs:
 
       - name: Start Appium Server
         run: |
-          npm install -g appium
+          if ! command -v appium &> /dev/null; then
+            echo "Appium not found, installing..."
+            npm install -g appium
+          else
+            echo "Appium is already installed."
+          fi
           appium --base-path /wd/hub &
 
       - run: npm root -g
